### ISSUE TITLE
Subcommand for runnig in terminal displaying the results only.

### ISSUE THREAD

**Issue by HappySquid25** [robot-rumble/cli#3]
It would be nice to have an option for running a game without getting any output besides the result of the battle. This would make testing bots a lot quicker.

**Comment by outkine** [comment]
Thank you for reporting! Fixed with https://github.com/robot-rumble/cli/commit/033bba46e5cea9a1b2c92347f40aa5389c3e032d, but there are some issues with building the cli so there will be a delay before there's a release with it

**Comment by outkine** [comment]
Included in https://github.com/robot-rumble/cli/releases/tag/v0.1-alpha.29.19 (linux only)
