### ISSUE TITLE
Absolute paths on windows cause issues

### ISSUE THREAD

**Issue by mousetail** [robot-rumble/cli#5]
When I run the CLI like this:

```
rumblebot.exe run term "C:\\Users\\Admin\\pypro\\genetic_robot\\bots_tmp\\bot_A.py" "C:\\Users\\Admin\\pypro\\genetic_robot\\bots_tmp\\bot_B.py"
```

I get the following error:

```
ERROR: Couldn't parse robot identifier
because: unknown runner type "C"
```

It seems to think the drive letter is a runner type.

**Comment by outkine** [comment]
Fixed with https://github.com/robot-rumble/cli/commit/886ba9e06b0003427a4cc003364d2cab43bd283f
